title = "הרפיית המאמץ"

[params]
    enableSourceMaps = true
    attribution = false
    [params.footer]
        [params.footer.links]
        [params.footer.contact_form]
            enabled = false

